config/routes.rb
Donne::Application.routes.draw do
  resources :nav_categories

  get '/digital_editions/:parent/new', to: 'digital_editions#new'
  get '/digital_editions/:parent/getitem', to: 'digital_editions#getitem'
  get '/digital_editions/:id/delobj', to: 'digital_editions#deledition'
  resources :digital_editions

  get '/trans/:id/fedit', to: 'trans#fedit'
  get '/trans/:parent/newtrans', to: 'trans#newtrans'
  get '/trans/:parent/getexpressions', to: 'trans#getexpressions'
  post '/transcriptions/update_order', to: 'transcriptions#update_order'
  post '/transcriptions/update_file', to: 'transcriptions#update'
  get '/transcriptions/:parent/newtrans', to: 'transcriptions#newtrans'
  get '/transcriptions/:id/dump', to: 'transcriptions#dump'
  resources :transcriptions

  get '/pages/:parent/view', to: 'pages#view'
  get '/pages/page', to: 'pages#page'
  get '/pages/:p/page/:parent', to: 'pages#page'
  get '/pages/:parent/new', to: 'pages#new'
  get '/pages/:id/edit', to: 'pages#edit'
  get '/pages/:parent/new', to: 'pages#new'
  get '/pages/:id/delobj', to: 'pages#delpage'
  resources :pages

  resources :surrogates

  resources :item_events

  get '/items/:parent/new', to: 'items#new'
  get '/items/:id/delobj', to: 'items#delitem'
  resources :items

  resources :manifestation_events

  resources :manifestations_events

  get '/manifestations/:parent/new', to: 'manifestations#new'
  get '/manifestations/:id/delobj', to: 'manifestations#delman'
  resources :manifestations
  
  
  get '/admin/:sub', to: 'admin#index'
  get '/admin', to: 'admin#index'
  post '/admin', to: 'admin#index'

  resources :system_event_types

  resources :local_markup_mappings

  resources :user_roles

  resources :confs

  get '/holding_institutions/:id/ref/:referer', to: 'holding_institutions#show'
  get '/holding_institutions/:referer/index', to: 'holding_institutions#index'
  get '/holding_institutions/:id/edit/:referer', to: 'holding_institutions#edit'
  get '/holding_institutions/:referer/new', to: 'holding_institutions#new'
  resources :holding_institutions
  
  get '/his/new', to: 'his#new'

  resources :manifestation_types

  resources :locations

  resources :agents

  resources :roles

  resources :event_types

  resources :expression_types
  
  get '/expressions/:parent/new', to: 'expressions#new'
  get '/expressions/:id/delobj', to: 'expressions#delexp'
  resources :expressions

  resources :entities

  get '/works/:id/delobj', to: 'works#delwork'
  resources :works

  resources :concordance_entries

  resources :concordance_stop_words
  
  match 'dotei/:id' => 'lines#dotei'

  resources :lines
  
  resource :secrets
  
  resource :users
  
  match 'login' => 'sessions#new'
  
  resource :sessions
  
  match 'sessions/destroy' => 'sessions#destroy'

  get '/splash', to: 'splash#index'

  get '/editions/:id', to: 'editions#show'
  get '/ed/:id', to: 'editions#show'

  get '/edition/:id/concordance', to: 'concordance#showedition'

  get 'edition/:id/concordance/:it', to: 'concordance#showeditem'

  get '/viewport/:id', to: 'view_port#show'
  get '/viewport/:id/:token', to: 'view_port#show'
  get '/viewport/:parent/page/:page', to: 'view_port#getpage'

  get '/doconcord/:id', to: 'concordance_entries#build_edition_concordance'

  get '/edition/:id/toc/:t', to: 'toc#showtoc'
  get '/edition/:id/toc', to: 'toc#showtoc'

  get '/utility/:id/tansrebuild', to: 'utility#update_lines'
  get '/utility/MakeMedThumb', to: 'utility#make_medium_thumb'

  root :to => 'splash#index'

  get '/zoom/:id', to: 'zoom#show'

end

app/controllers/manifestation_types_controller.rb
###############################################################################
#    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
#                                                                             #
#    This file is part of the Collex Edition Builder, a platform              #
#    publishing digital editions with a complete, FRBRized system of          #
#    metadata management and linked-data functionality.                       #
#                                                                             #
#    The Collex Edition Builder is free software: you can redistribute it     #
#    and/or modify it under the terms of the GNU General Public License       #
#    as published by the Free Software Foundation, either version 3 of        #
#    the License, or (at your option) any later version.                      #
#                                                                             #
#    The Collex Edition Builder is distributed in the hope that it will       #
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
#    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with The Collex Edition Builder distribution.  If not,             #
#    see <http://www.gnu.org/licenses/>.                                      #
#                                                                             #
#    Development of this software was made possible through funding from      #
#    the National Endowment for the Humanities as well as the Institute       #
#    for Digital Humanities, Media, and Culture at Texas A&M University.      #
###############################################################################
class ManifestationTypesController < ApplicationController
  # GET /manifestation_types
  # GET /manifestation_types.json
  def index
    @manifestation_types = ManifestationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @manifestation_types }
    end
  end

  # GET /manifestation_types/1
  # GET /manifestation_types/1.json
  def show
    @manifestation_type = ManifestationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manifestation_type }
    end
  end

  # GET /manifestation_types/new
  # GET /manifestation_types/new.json
  def new
    @manifestation_type = ManifestationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manifestation_type }
    end
  end

  # GET /manifestation_types/1/edit
  def edit
    @manifestation_type = ManifestationType.find(params[:id])
  end

  # POST /manifestation_types
  # POST /manifestation_types.json
  def create
    @manifestation_type = ManifestationType.new(params[:manifestation_type])

    respond_to do |format|
      if @manifestation_type.save
        format.html { redirect_to @manifestation_type, notice: 'Manifestation type was successfully created.' }
        format.json { render json: @manifestation_type, status: :created, location: @manifestation_type }
      else
        format.html { render action: "new" }
        format.json { render json: @manifestation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /manifestation_types/1
  # PUT /manifestation_types/1.json
  def update
    @manifestation_type = ManifestationType.find(params[:id])

    respond_to do |format|
      if @manifestation_type.update_attributes(params[:manifestation_type])
        format.html { redirect_to @manifestation_type, notice: 'Manifestation type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manifestation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manifestation_types/1
  # DELETE /manifestation_types/1.json
  def destroy
    @manifestation_type = ManifestationType.find(params[:id])
    @manifestation_type.destroy

    respond_to do |format|
      format.html { redirect_to manifestation_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/manifestation_types_helper.rb
###############################################################################
#    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
#                                                                             #
#    This file is part of the Collex Edition Builder, a platform              #
#    publishing digital editions with a complete, FRBRized system of          #
#    metadata management and linked-data functionality.                       #
#                                                                             #
#    The Collex Edition Builder is free software: you can redistribute it     #
#    and/or modify it under the terms of the GNU General Public License       #
#    as published by the Free Software Foundation, either version 3 of        #
#    the License, or (at your option) any later version.                      #
#                                                                             #
#    The Collex Edition Builder is distributed in the hope that it will       #
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
#    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with The Collex Edition Builder distribution.  If not,             #
#    see <http://www.gnu.org/licenses/>.                                      #
#                                                                             #
#    Development of this software was made possible through funding from      #
#    the National Endowment for the Humanities as well as the Institute       #
#    for Digital Humanities, Media, and Culture at Texas A&M University.      #
###############################################################################
module ManifestationTypesHelper
end

app/views/manifestation_types/_form.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<%= form_for(@manifestation_type) do |f| %>
  <% if @manifestation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manifestation_type.errors.count, "error") %> prohibited this manifestation_type from being saved:</h2>

      <ul>
      <% @manifestation_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manifestation_type_type %><br />
    <%= f.text_field :manifestation_type_type %>
  </div>
  <div class="field">
    <%= f.label :manifestation_type_description %><br />
    <%= f.text_field :manifestation_type_description %>
  </div>
  <div class="field">
    <%= f.label :manifestation_type_notes %><br />
    <%= f.text_area :manifestation_type_notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manifestation_types/edit.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<h1>Editing manifestation_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @manifestation_type %> |
<%= link_to 'Back', manifestation_types_path %>

app/views/manifestation_types/index.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<h1>Listing manifestation_types</h1>

<table>
  <tr>
    <th>Manifestation type type</th>
    <th>Manifestation type description</th>
    <th>Manifestation type notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @manifestation_types.each do |manifestation_type| %>
  <tr>
    <td><%= manifestation_type.manifestation_type_type %></td>
    <td><%= manifestation_type.manifestation_type_description %></td>
    <td><%= manifestation_type.manifestation_type_notes %></td>
    <td><%= link_to 'Show', manifestation_type %></td>
    <td><%= link_to 'Edit', edit_manifestation_type_path(manifestation_type) %></td>
    <td><%= link_to 'Destroy', manifestation_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Manifestation type', new_manifestation_type_path %>

app/views/manifestation_types/new.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<h1>New manifestation_type</h1>

<%= render 'form' %>

<%= link_to 'Back', manifestation_types_path %>

app/views/manifestation_types/show.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<p id="notice"><%= notice %></p>

<p>
  <b>Manifestation type type:</b>
  <%= @manifestation_type.manifestation_type_type %>
</p>

<p>
  <b>Manifestation type description:</b>
  <%= @manifestation_type.manifestation_type_description %>
</p>

<p>
  <b>Manifestation type notes:</b>
  <%= @manifestation_type.manifestation_type_notes %>
</p>


<%= link_to 'Edit', edit_manifestation_type_path(@manifestation_type) %> |
<%= link_to 'Back', manifestation_types_path %>