config/routes.rb
Donne::Application.routes.draw do
  resources :nav_categories

  get '/digital_editions/:parent/new', to: 'digital_editions#new'
  get '/digital_editions/:parent/getitem', to: 'digital_editions#getitem'
  get '/digital_editions/:id/delobj', to: 'digital_editions#deledition'
  resources :digital_editions

  get '/trans/:id/fedit', to: 'trans#fedit'
  get '/trans/:parent/newtrans', to: 'trans#newtrans'
  get '/trans/:parent/getexpressions', to: 'trans#getexpressions'
  post '/transcriptions/update_order', to: 'transcriptions#update_order'
  post '/transcriptions/update_file', to: 'transcriptions#update'
  get '/transcriptions/:parent/newtrans', to: 'transcriptions#newtrans'
  get '/transcriptions/:id/dump', to: 'transcriptions#dump'
  resources :transcriptions

  get '/pages/:parent/view', to: 'pages#view'
  get '/pages/page', to: 'pages#page'
  get '/pages/:p/page/:parent', to: 'pages#page'
  get '/pages/:parent/new', to: 'pages#new'
  get '/pages/:id/edit', to: 'pages#edit'
  get '/pages/:parent/new', to: 'pages#new'
  get '/pages/:id/delobj', to: 'pages#delpage'
  resources :pages

  resources :surrogates

  resources :item_events

  get '/items/:parent/new', to: 'items#new'
  get '/items/:id/delobj', to: 'items#delitem'
  resources :items

  resources :manifestation_events

  resources :manifestations_events

  get '/manifestations/:parent/new', to: 'manifestations#new'
  get '/manifestations/:id/delobj', to: 'manifestations#delman'
  resources :manifestations
  
  
  get '/admin/:sub', to: 'admin#index'
  get '/admin', to: 'admin#index'
  post '/admin', to: 'admin#index'

  resources :system_event_types

  resources :local_markup_mappings

  resources :user_roles

  resources :confs

  get '/holding_institutions/:id/ref/:referer', to: 'holding_institutions#show'
  get '/holding_institutions/:referer/index', to: 'holding_institutions#index'
  get '/holding_institutions/:id/edit/:referer', to: 'holding_institutions#edit'
  get '/holding_institutions/:referer/new', to: 'holding_institutions#new'
  resources :holding_institutions
  
  get '/his/new', to: 'his#new'

  resources :manifestation_types

  resources :locations

  resources :agents

  resources :roles

  resources :event_types

  resources :expression_types
  
  get '/expressions/:parent/new', to: 'expressions#new'
  get '/expressions/:id/delobj', to: 'expressions#delexp'
  resources :expressions

  resources :entities

  get '/works/:id/delobj', to: 'works#delwork'
  resources :works

  resources :concordance_entries

  resources :concordance_stop_words
  
  match 'dotei/:id' => 'lines#dotei'

  resources :lines
  
  resource :secrets
  
  resource :users
  
  match 'login' => 'sessions#new'
  
  resource :sessions
  
  match 'sessions/destroy' => 'sessions#destroy'

  get '/splash', to: 'splash#index'

  get '/editions/:id', to: 'editions#show'
  get '/ed/:id', to: 'editions#show'

  get '/edition/:id/concordance', to: 'concordance#showedition'

  get 'edition/:id/concordance/:it', to: 'concordance#showeditem'

  get '/viewport/:id', to: 'view_port#show'
  get '/viewport/:id/:token', to: 'view_port#show'
  get '/viewport/:parent/page/:page', to: 'view_port#getpage'

  get '/doconcord/:id', to: 'concordance_entries#build_edition_concordance'

  get '/edition/:id/toc/:t', to: 'toc#showtoc'
  get '/edition/:id/toc', to: 'toc#showtoc'

  get '/utility/:id/tansrebuild', to: 'utility#update_lines'
  get '/utility/MakeMedThumb', to: 'utility#make_medium_thumb'

  root :to => 'splash#index'

  get '/zoom/:id', to: 'zoom#show'

end

app/models/nav_category.rb
###############################################################################
#    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
#                                                                             #
#    This file is part of the Collex Edition Builder, a platform              #
#    publishing digital editions with a complete, FRBRized system of          #
#    metadata management and linked-data functionality.                       #
#                                                                             #
#    The Collex Edition Builder is free software: you can redistribute it     #
#    and/or modify it under the terms of the GNU General Public License       #
#    as published by the Free Software Foundation, either version 3 of        #
#    the License, or (at your option) any later version.                      #
#                                                                             #
#    The Collex Edition Builder is distributed in the hope that it will       #
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
#    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with The Collex Edition Builder distribution.  If not,             #
#    see <http://www.gnu.org/licenses/>.                                      #
#                                                                             #
#    Development of this software was made possible through funding from      #
#    the National Endowment for the Humanities as well as the Institute       #
#    for Digital Humanities, Media, and Culture at Texas A&M University.      #
###############################################################################
class NavCategory < ActiveRecord::Base
  attr_accessible :id, :nav_category_name, :nav_category_order
  has_many :digital_editions,  :inverse_of => :nav_categories
end

app/controllers/nav_categories_controller.rb
###############################################################################
#    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
#                                                                             #
#    This file is part of the Collex Edition Builder, a platform              #
#    publishing digital editions with a complete, FRBRized system of          #
#    metadata management and linked-data functionality.                       #
#                                                                             #
#    The Collex Edition Builder is free software: you can redistribute it     #
#    and/or modify it under the terms of the GNU General Public License       #
#    as published by the Free Software Foundation, either version 3 of        #
#    the License, or (at your option) any later version.                      #
#                                                                             #
#    The Collex Edition Builder is distributed in the hope that it will       #
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
#    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with The Collex Edition Builder distribution.  If not,             #
#    see <http://www.gnu.org/licenses/>.                                      #
#                                                                             #
#    Development of this software was made possible through funding from      #
#    the National Endowment for the Humanities as well as the Institute       #
#    for Digital Humanities, Media, and Culture at Texas A&M University.      #
###############################################################################
class NavCategoriesController < ApplicationController
  # GET /nav_categories
  # GET /nav_categories.json
  def index
    @nav_categories = NavCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nav_categories }
    end
  end

  # GET /nav_categories/1
  # GET /nav_categories/1.json
  def show
    @nav_category = NavCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nav_category }
    end
  end

  # GET /nav_categories/new
  # GET /nav_categories/new.json
  def new
    @nav_category = NavCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nav_category }
    end
  end

  # GET /nav_categories/1/edit
  def edit
    @nav_category = NavCategory.find(params[:id])
  end

  # POST /nav_categories
  # POST /nav_categories.json
  def create
    @nav_category = NavCategory.new(params[:nav_category])

    respond_to do |format|
      if @nav_category.save
        format.html { redirect_to @nav_category, notice: 'Nav category was successfully created.' }
        format.json { render json: @nav_category, status: :created, location: @nav_category }
      else
        format.html { render action: "new" }
        format.json { render json: @nav_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nav_categories/1
  # PUT /nav_categories/1.json
  def update
    @nav_category = NavCategory.find(params[:id])

    respond_to do |format|
      if @nav_category.update_attributes(params[:nav_category])
        format.html { redirect_to @nav_category, notice: 'Nav category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nav_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nav_categories/1
  # DELETE /nav_categories/1.json
  def destroy
    @nav_category = NavCategory.find(params[:id])
    @nav_category.destroy

    respond_to do |format|
      format.html { redirect_to nav_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nav_categories_helper.rb
###############################################################################
#    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
#                                                                             #
#    This file is part of the Collex Edition Builder, a platform              #
#    publishing digital editions with a complete, FRBRized system of          #
#    metadata management and linked-data functionality.                       #
#                                                                             #
#    The Collex Edition Builder is free software: you can redistribute it     #
#    and/or modify it under the terms of the GNU General Public License       #
#    as published by the Free Software Foundation, either version 3 of        #
#    the License, or (at your option) any later version.                      #
#                                                                             #
#    The Collex Edition Builder is distributed in the hope that it will       #
#    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
#    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with The Collex Edition Builder distribution.  If not,             #
#    see <http://www.gnu.org/licenses/>.                                      #
#                                                                             #
#    Development of this software was made possible through funding from      #
#    the National Endowment for the Humanities as well as the Institute       #
#    for Digital Humanities, Media, and Culture at Texas A&M University.      #
###############################################################################
module NavCategoriesHelper
end

app/views/nav_categories/_form.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<%= form_for(@nav_category) do |f| %>
  <% if @nav_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nav_category.errors.count, "error") %> prohibited this nav_category from being saved:</h2>

      <ul>
      <% @nav_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nav_category_name %><br />
    <%= f.text_field :nav_category_name %>
  </div>
  <div class="field">
    <%= f.label :nav_category_order %><br />
    <%= f.number_field :nav_category_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nav_categories/edit.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<h1>Editing nav_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @nav_category %> |
<%= link_to 'Back', nav_categories_path %>

app/views/nav_categories/index.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<h1>Listing nav_categories</h1>

<table>
  <tr>
    <th>Nav category name</th>
    <th>Nav category order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nav_categories.each do |nav_category| %>
  <tr>
    <td><%= nav_category.nav_category_name %></td>
    <td><%= nav_category.nav_category_order %></td>
    <td><%= link_to 'Show', nav_category %></td>
    <td><%= link_to 'Edit', edit_nav_category_path(nav_category) %></td>
    <td><%= link_to 'Destroy', nav_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nav category', new_nav_category_path %>

app/views/nav_categories/new.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<h1>New nav_category</h1>

<%= render 'form' %>

<%= link_to 'Back', nav_categories_path %>

app/views/nav_categories/show.html.erb
<%=begin
     ###############################################################################
     #    Copyright (c) 2014, Carl Stahmer - www.carlstahmer.com                   #
     #                                                                             #
     #    This file is part of the Collex Edition Builder, a platform              #
     #    publishing digital editions with a complete, FRBRized system of          #
     #    metadata management and linked-data functionality.                       #
     #                                                                             #
     #    The Collex Edition Builder is free software: you can redistribute it     #
     #    and/or modify it under the terms of the GNU General Public License       #
     #    as published by the Free Software Foundation, either version 3 of        #
     #    the License, or (at your option) any later version.                      #
     #                                                                             #
     #    The Collex Edition Builder is distributed in the hope that it will       #
     #    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty   #
     #    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
     #    GNU General Public License for more details.                             #
     #                                                                             #
     #    You should have received a copy of the GNU General Public License        #
     #    along with The Collex Edition Builder distribution.  If not,             #
     #    see <http://www.gnu.org/licenses/>.                                      #
     #                                                                             #
     #    Development of this software was made possible through funding from      #
     #    the National Endowment for the Humanities as well as the Institute       #
     #    for Digital Humanities, Media, and Culture at Texas A&M University.      #
     ###############################################################################
   end%>
<p id="notice"><%= notice %></p>

<p>
  <b>Nav category name:</b>
  <%= @nav_category.nav_category_name %>
</p>

<p>
  <b>Nav category order:</b>
  <%= @nav_category.nav_category_order %>
</p>


<%= link_to 'Edit', edit_nav_category_path(@nav_category) %> |
<%= link_to 'Back', nav_categories_path %>